{% set name = "spacy-pkuseg" %}
{% set modulename = "spacy_pkuseg" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/{{ name }}/{{ modulename }}-{{ version }}.tar.gz
  sha256: 33531ea8e13fc09ebe3b40bd97e84d07ccd5a1fe67fa8e84173769a25ac03158

build:
  number: 0
  skip: True  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
    - cython >=0.25
    - numpy >=2.0.0,<3.0.0
  run:
    - python
    - numpy >=2.0.0,<3.0.0
    - srsly >=2.3.0,<3.0.0

test:
  imports:
    - {{ modulename }}
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - python -m pytest --tb=native --pyargs {{ modulename }}

about:
  home: https://github.com/explosion/spacy-pkuseg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: PKUSeg Chinese word segmentation toolkit for spaCy
  description: |
    This package is a fork of pkuseg-python that simplifies installation
    and serialization for use with spaCy. The underlying segmentation
    tools remain unmodified.
  doc_url: https://github.com/explosion/spacy-pkuseg/blob/master/readme/readme_english.md
  dev_url: https://github.com/explosion/spacy-pkuseg

extra:
  recipe-maintainers:
    - ines
    - honnibal
    - adrianeboyd
